# Generated by Django 4.2.4 on 2023-08-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_forum_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
