# Generated by Django 4.2.4 on 2023-08-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='forum_id',
            new_name='forum',
        ),
    ]
