# Generated by Django 4.2.4 on 2023-08-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_rename_forum_id_comments_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(),
        ),
    ]
