# Generated by Django 4.2.4 on 2023-08-09 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_forum_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0007_alter_comments_forum_alter_comments_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('created',)},
        ),
        migrations.AlterField(
            model_name='comments',
            name='forum',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='forum.forum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
