# Generated by Django 4.2.4 on 2023-08-09 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_comments_options_alter_comments_forum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
