# Generated by Django 4.2.4 on 2023-08-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_comments_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-created',)},
        ),
    ]
