# Generated by Django 4.2.4 on 2023-08-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_customuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateTimeField(default='2000-03-20'),
            preserve_default=False,
        ),
    ]
