# Generated by Django 4.2.4 on 2023-08-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='residency',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
