# Generated by Django 4.2.4 on 2023-08-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_customuser_residency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='residency',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
