# Generated by Django 4.2.4 on 2023-08-09 07:09

import MOTIVE_project.profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[MOTIVE_project.profiles.validators.EmailValidator]),
        ),
    ]
