# Generated by Django 4.2.4 on 2023-08-17 17:12

import MOTIVE_project.profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=40, validators=[MOTIVE_project.profiles.validators.username_validator]),
        ),
    ]
