# Generated by Django 4.2.4 on 2023-08-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
