# Generated by Django 4.2.4 on 2023-08-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='host',
        ),
    ]
