# Generated by Django 4.2.4 on 2023-08-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forum_host_forum_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='members',
        ),
        migrations.AlterField(
            model_name='forum',
            name='host',
            field=models.CharField(default='default host name', max_length=30),
            preserve_default=False,
        ),
    ]
