# Generated by Django 4.2.4 on 2023-08-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_forum_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='rating',
            field=models.CharField(blank=True, choices=[('1-star', '1'), ('1-star', '2'), ('3-star', '3'), ('4-star', '4'), ('5-star', '5')], max_length=10, null=True),
        ),
    ]
