# Generated by Django 4.2.4 on 2023-08-15 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0010_alter_forum_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.CharField(choices=[('1-star', '1'), ('1-star', '2'), ('3-star', '3'), ('4-star', '4'), ('5-star', '5')], max_length=20)),
                ('forum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.forum')),
                ('voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('voter', 'forum')},
            },
        ),
    ]
