# Generated by Django 4.2.4 on 2023-08-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_alter_forumratings_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('1', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20, null=True),
        ),
    ]
