# Generated by Django 4.2.4 on 2023-08-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_alter_forum_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumratings',
            name='ratings',
            field=models.CharField(choices=[('1', '1'), ('1', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20),
        ),
    ]
