# Generated by Django 4.2.4 on 2023-08-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_alter_forumratings_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='rating',
        ),
        migrations.AddField(
            model_name='forum',
            name='average_rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='ratings_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
