# Generated by Django 4.2.4 on 2023-08-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_remove_forum_rating_forum_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
