# Generated by Django 4.2.4 on 2023-08-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_alter_forum_average_rating_alter_forum_ratings_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumratings',
            name='ratings',
            field=models.CharField(blank=True, choices=[('1', '1'), ('1', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20, null=True),
        ),
    ]
