# Generated by Django 4.2.4 on 2023-08-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_alter_forumratings_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='forum_main_images'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='side_image',
            field=models.FileField(blank=True, null=True, upload_to='forum_side_images'),
        ),
    ]
