# Generated by Django 4.2.4 on 2023-08-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_alter_forum_main_image_alter_forum_side_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
