# Generated by Django 4.2.4 on 2023-08-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_alter_forum_description_alter_forum_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ('pk',), 'verbose_name': 'Topics'},
        ),
    ]
