# Generated by Django 4.2.4 on 2023-08-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_alter_topics_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumratings',
            options={'verbose_name': 'ForumRating'},
        ),
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ('pk',), 'verbose_name': 'Topic'},
        ),
    ]
